server:
  port: 8080
spring:
  datasource:
    username: root
    password: xxxxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.91.155.174:3306/ape?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
sql:
  beauty:
    show: false
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

db:
  router:
    config: classpath:ape-sharding.yml
    master:
      url: jdbc:mysql://119.91.155.174:3306/ape?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      user-name: root
      password: xxxxxxxx
    dbs:
      - url: jdbc:mysql://119.91.155.174:3306/loser_01?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        user-name: root
        password: xxxxxxxx
      - url: jdbc:mysql://119.91.155.174:3306/loser_02?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        user-name: root
        password: xxxxxxxx
